#!/usr/bin/with-contenv bash

set -e
cd /config/www/freshrss/extensions

if [ -d .git-youtube ]; then
  echo removing freshrss-youtube, it is now part of freshrss-extensions
  rm -rf .git-youtube xExtension-YouTube
fi
