name: Docker
on: [push, workflow_dispatch]

permissions:
  contents: read
  packages: write

env:
  IMAGE_AUTHOR: mentalfs
  IMAGE_NAME: linuxserver-mods


jobs:
  freshrss-extensions:
    uses: ./.github/workflows/image.yml
    with:
      path: freshrss-extensions
      tag: freshrss-extensions
    secrets: inherit


  freshrss-comicsinfeed:
    uses: ./.github/workflows/image.yml
    with:
      path: freshrss-comicsinfeed
      tag: freshrss-comicsinfeed
    secrets: inherit


  freshrss-redditsub:
    uses: ./.github/workflows/image.yml
    with:
      path: freshrss-redditsub
      tag: freshrss-redditsub
    secrets: inherit


  freshrss-all:
    needs:
      - freshrss-extensions
      - freshrss-comicsinfeed
      - freshrss-redditsub
    uses: ./.github/workflows/image.yml
    with:
      path: freshrss-*
      tag: freshrss-all
    secrets: inherit


  prune:
    if: ${{ github.ref == 'refs/heads/main' }}
    needs:
      - freshrss-all
    runs-on: ubuntu-latest

    steps:
      - name: Delete untagged images
        uses: actions/delete-package-versions@v5
        with:
          package-name: ${{ env.IMAGE_NAME }}
          package-type: container
          delete-only-untagged-versions: 'true'
          token: ${{ secrets.GITHUB_TOKEN }}
