name: Docker
on: [push, workflow_dispatch]

permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io
  IMAGE_AUTHOR: mentalfs
  IMAGE_NAME: linuxserver-mods

jobs:
  freshrss-extensions:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Log into registry ${{ env.REGISTRY }}
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_AUTHOR }}/${{ env.IMAGE_NAME }}
          tags:   freshrss-extensions

      - name: Build and push it to ${{ env.REGISTRY }}
        id: build-and-push
        uses: docker/build-push-action@v5
        with:
          context: ./freshrss-extensions
          file: ./freshrss-extensions/Dockerfile
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_AUTHOR }}/${{ env.IMAGE_NAME }}:freshrss-extensions
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: ${{ github.ref == 'refs/heads/main' }}


  freshrss-redditimage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Log into registry ${{ env.REGISTRY }}
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_AUTHOR }}/${{ env.IMAGE_NAME }}
          tags:   freshrss-redditimage

      - name: Build and push it to ${{ env.REGISTRY }}
        id: build-and-push
        uses: docker/build-push-action@v5
        with:
          context: ./freshrss-redditimage
          file: ./freshrss-redditimage/Dockerfile
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_AUTHOR }}/${{ env.IMAGE_NAME }}:freshrss-redditimage
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: ${{ github.ref == 'refs/heads/main' }}


  prune:
    needs: [freshrss-extensions, freshrss-redditimage]
    runs-on: ubuntu-latest

    steps:
      - name: Prune old untagged images
        uses: vlaurin/action-ghcr-prune@v0.5.0
        with:
          token: ${{ secrets.PACKAGE_DELETE_TOKEN }}
          user: ${{ env.IMAGE_AUTHOR }}
          container: ${{ env.IMAGE_NAME }}
          dry-run: false
          prune-untagged: true
