name: Image

on:
  workflow_call:
    inputs:
      path:
        required: true
        type: string
      tag:
        required: true
        type: string

permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io
  IMAGE_AUTHOR: mentalfs
  IMAGE_NAME: linuxserver-mods


jobs:
  image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Log into registry ${{ env.REGISTRY }}
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_AUTHOR }}/${{ env.IMAGE_NAME }}:${{ inputs.tag }}

      - name: Build and push it to ${{ env.REGISTRY }}
        id: build-and-push
        uses: docker/build-push-action@v5
        with:
          context: .
          build-args: MOD=${{ inputs.path }}
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_AUTHOR }}/${{ env.IMAGE_NAME }}:${{ inputs.tag }}
          labels: ${{ steps.meta.outputs.labels }}
          provenance: false
          push: ${{ github.ref == 'refs/heads/main' }}
          cache-from: type=gha
          cache-to: type=gha,mode=max


